# Book Cover


# Backpage
- First one or two paragraphs should present background, aims and scope, and what sets the book apart.
- Third (or second, if only one above) paragraph is actually a bulleted list of the key features (try to be as specific as possible).
- Final paragraph is a summary including audience (although this may feature at the beginning).
- If there is room, you can include a short author bio at the end.

## 1/2
This book provides solutions to the exercises offered in Advanced R (Wickham, 2019) and reflects our effort to understand and learn the content presented in it.

it is written 

solutions manual

## specific key features
This book will help you
- deepen your understanding of the R language, by
- keep you motivated, when working through Advanced R
- provide alternative solutions
- give you another perspective on the content
- our experience and learnings working through Advanced R 

## summary and audience
The book hopes to be a companion and resource to move your journey in programming in the R language forward.

The content may be helpful to R users, interested in sharpening their understanding of the programming language.

# Author Bios (75-100 words long each)
### Malte Grosser


### Henning Bumann
As a psychologist and statistician Henning enjoys making sense of data and is motivated to build data-driven solutions that are both beautiful and meaningful. He prefers free programming tools to support effective and transparent collaboration. He is happy to be an active member of the R community and considers learning to code one of the most fortunate junctions in his professional life. Away from the computer Henning likes to take it easy and spend time in nature and with family and friends.

- maybe mention Hamburg
- build and contribute together
- improve his coding habits
- eager to learn new things

### Hadley Wickham (from Adv R)
Hadley Wickham is Chief Scientist at RStudio, an Adjunct Professor at Stanford University and the University of Auckland, and a member of the R Foundation. He is the lead developer of the tidyverse, a collection of R packages, including ggplot2 and dplyr, designed to support data science. He is also the author of R for Data Science (with Garrett Grolemund), R Packages, and ggplot2: Elegant Graphics for Data Analysis.