## Backpage Malte (88 Zeichen pro Zeile, 39 Zeilen)
> “I learned a lot working through their solutions — it's a great way to broaden and deepen your understanding of R. (I should probably go through it again...)”

- Greg Wilson | RStudio, PBC
<!-- Source: https://twitter.com/gvwilson/status/1119235643652157440 -->

This book offers solutions to all 284 exercises in Advanced R. It is based on our own efforts to work through Advanced R to learn the R programming language as efficiently and sustainably as possible. To this end, we have carefully documented all our solutions and made them as understandable and clear as possible. All solutions were carefully reviewed by Hadley Wickham, who also helped us when some exercises seemed unsolvable at first.

Working through the exercises and their solutions will give you a deep understanding of a variety of programming problems, many of which you might encounter in your daily work. It will give you a great set of tools to solve many of these problems not only technically but also conceptually. In the process, you will develop a good sense of identifying and comparing different approaches. While in some situations you will be able to transfer certain programming schemes directly, in many others far more elegant options might open up to you. As a positive side effect, your fluency in R will notably increase.

From a technical and R-specific perspective, you will learn about:

* When R makes copies, how this affects memory and performance, and how to address this.
* The characteristics of base R's vector data types and the implications.
* How to choose between R's different subsetting options.
* Everything you could ever want to know about functions in R.
* How to use rlang to work with environments and how to recurse over environments.
* The differences between calling and exiting handlers.
* How to employ functional programming to efficiently solve modular tasks involving, e.g., iterations or parameterisations.
* The mechanics, usage and limitations of R's commonly used and highly pragmatic S3 OO system.
* When and how to work with the R6 OO system, which takes a more classical and structured approach to OO programming, and should feel very natural if you already know OO programming from other languages.
* Working with R's S4 OO system, which extends S3 with multiple dispatch and inheritance and much stricter formalities.
* How R parses expressions into abstract syntax trees and evaluates their elements.
* How you can modify these elements and even change their environments within this process.
* How to use this technique to create domain specific languages such as HTML or LaTeX purely based on systematic conversion of R code.
* How to identify performance bottlenecks via profiling and to compare different approaches via benchmarks.
* Different strategies for optimising R code, such as using pre-optimised functions, vectorisation, using solutions from e.g. algebra or simply reducing the scope of a function.
* Rewriting R code in C++ via the Rcpp package.

Malte Grosser is a business mathematician from Hamburg, who has been programming in R regularly since the beginning of his career. He is currently finishing his PhD on machine learning for stroke outcome prediction from medical images and develops solutions in business as a Data Scientist. Malte likes to promote and engage in the local R community and is the author of the snakecase package, which converts strings into arbitrary cases.

Henning Bumann is a psychologist and statistician who enjoys making sense of data and is motivated to build data-driven solutions that are beautiful and meaningful. He prefers free programming tools to support effective and transparent collaboration. He is happy to be an active member of the Hamburg R community and considers learning to code one of the most fortunate junctions in his professional life. Away from the computer Henning likes to take it easy and spend time in nature and with family and friends.

Hadley Wickham is the original author of Advanced R and helped us by lightly reviewing the proposed answers.

## (Or longer version from Advanced R

Hadley Wickham is Chief Scientist at RStudio, an Adjunct Professor at Stanford University and the University of Auckland, and a member of the R Foundation. He is the lead developer of the tidyverse, a collection of R packages, including ggplot2 and dplyr, designed to support data science. He is also the author of R for Data Science (with Garrett Grolemund), R Packages, and ggplot2: Elegant Graphics for Data Analysis.)