# Book Cover

# Backpage
## Requirements/ Guidance from C&H
- First one or two paragraphs should present background, aims and scope, and what sets the book apart.
- Third (or second, if only one above) paragraph is actually a bulleted list of the key features (try to be as specific as possible).
- Final paragraph is a summary including audience (although this may feature at the beginning).
- If there is room, you can include a short author bio at the end.

## gemeinsames Proposal
> “I learned a lot working through their solutions — it's a great way to broaden and deepen your understanding of R. (I should probably go through it again…)”

- Greg Wilson | RStudio, PBC
<!-- Source: https://twitter.com/gvwilson/status/1119235643652157440 -->

### Paragraph 1/2
This book provides solutions to the exercises posed in the 2nd Edition of Advanced R (Wickham, 2019). Advanced R introduces programmers and R users to various aspects of modern R programming. It also presents many challenging problems to test and expand your knowledge of the R language and important programming paradigms.

This solutions manual will help you make the most of these exercises and offers a convenient point of reference. The entire content has been carefully prepared and revised with the help of Hadley Wickham.

### specific key features
This book will support your study of the R language and
- provide worked solutions to all 284 exercises presented in Advanced R
- discuss implementation details and alternative solutions
- help you stay motivated and avoid getting stuck
- serves as a reference to check your own solutions
- summarise our own experience and learnings with the content

### summary and audience
This book can provide a helpful resource for anyone interested in deepening their understanding of programming and the R language through Advanced R.

# Author Bios (75-100 words long each)
### Malte Grosser
Malte Grosser is a business mathematician from Hamburg, who has been programming in R regularly since the beginning of his career. He is currently finishing his PhD on machine learning for stroke outcome prediction from medical images and develops solutions in business as a Data Scientist. Malte likes to promote and engage in the local R community and is the author of the snakecase package, which converts strings into arbitrary cases.

<!-- - His eagerness to solve problems at the root and continually improve his coding skill led him to "Advanced R" and from there to "Advanced R Solutions". -->

### Henning Bumann
As a psychologist and statistician Henning enjoys making sense of data and is motivated to build data-driven solutions that are both beautiful and meaningful. He prefers free programming tools to support effective and transparent collaboration. He is happy to be an active member of the Hamburg R community and considers learning to code one of the most fortunate junctions in his professional life. Away from the computer Henning likes to take it easy and spend time in nature and with family and friends.

### Hadley Wickham (from Adv R)
Hadley Wickham is Chief Scientist at RStudio, an Adjunct Professor at Stanford University and the University of Auckland, and a member of the R Foundation. He is the lead developer of the tidyverse, a collection of R packages, including ggplot2 and dplyr, designed to support data science. He is also the author of R for Data Science (with Garrett Grolemund), R Packages, and ggplot2: Elegant Graphics for Data Analysis.


# Maltes initiales Proposal für die Backpage
Do you want to deepen your R-skills and build up knowledge to master the application of R from the bottom up?

Advanced R Solutions gives you a great boost to fully internalise Hadley Wickham's Advanced R and benefit enormously from it in your everyday work.

Advanced R provides programmers from all backgrounds with a comprehensive introduction into the world of professional R programming. It shows that, “despite its sometimes frustrating quirks, R is, at its heart, an elegant and beautiful language, well tailored for data science”. It gives you an entry to dive into the material yourself with almost 300(!) exercises, which are provided throughout its chapters.

Advanced R Solutions supports you on this journey with appropriately detailed solutions for each of these exercises. The entire content, including the R-code, has been carefully prepared and revised with the help of Hadley Wickham.