\mainmatter

# Preface
This book provides solutions to the exercises offered in Advanced R (2nd Edition, Wickham, 2019) and reflects our effort to understand and acquire the content presented in it.

Advanced R covers R and programming. It presents the specific characteristics of the R language to programmers and helps R users to improve their understanding of general programming concepts. 

When we came across Advanced R we found, that it gave us a more thorough understanding of the R code we worked with daily and helped us see the underlying principles more clearly. The content helped us get a more complete picture/ map of the landscape of programming with R and was presented accessible and relevant way.

We soon re-discovered that reading about programming is not enough and that it helps greatly to open the editor and write some code along the way. The clear structure of Advanced R and the exercises given provided a great starting point for this.

We think of this book as a solutions manual, which intends to supplement and support your study of the R language through Advanced R. We hope that it will help you to stay on track while working through Advanced R and allow you to check your understanding and progress along the way. The solutions may also give you another perspective on the material presented.

## How this book came to be
The solutions in this book are written from our personal perspective and current level of understanding. We both come from quantitative backgrounds (mathematics/ statistics) preparing us more carefully for data analysis than for programming. So we were R users first and improved as programmers in our day jobs and also through working on this project.

We took advantage of the `{bookdown}` package to structure this process and create a book almost as a by-product. The initial progress was fun and motivating. To actually provide solutions to all the 284 exercises in the book took slightly longer (and Hadley's rewriting of Advanced R halfway in between didn't really make the journey shorter).

As the project matured we strived to provide solutions as clean, straightforward and expressive as possible. A lot of the solutions actually consist of mostly code, as we gave it preference to lengthy explanations. The written explanations aim to fill in context and motivation, discuss important implementation details or relate to the practical work of being an R programmer.

Hadley Wickham wrote Advanced R and created the exercises which form the substructure of this book. We took the task to solve them as correctly and idiomatically as possible. When we finished a chapter we asked Hadley to review it. His feedback included many comments (which we then had to resolve), corrections and suggestions, as well as a few complete solutions.

We repeated this process until each exercise was reviewed and approved. As a result we have a fairly good feeling about the solutions in the book. But any remaining mistakes or inconsistencies are certainly on us.

## How to use this book
Because this book builds so heavily on Advanced R we think it should be read together with the textbook, either as as a hardcopy or in the online version (https://adv-r.hadley.nz). Working on the exercises by yourself first generally should give you the biggest benefit.

It may be a good idea to start with the parts of Advanced R that are most relevant to your work and interest. You can certainly read the book cover to cover, but we think that you don't have to, though it's probably a good idea to start with the Foundations-part first.

Of the more difficult exercises in the book only a few were finished in one session. We often had to re-read the question, check up on the related content in Advanced R and started by writing a few first lines code or consulted the documentation. Reading the source code (preferably with syntax highlighting) and searching the web were typically also quite helpful in the process.

To support your study, you may also be interested in the [R4DS Advanced R Bookclub](https://GitHub.com/r4ds/bookclub-Advanced_R), where a different chapters of the textbook are discussed with other programmers every week.

In case you want to do more or are have a special interest in the mechanics of base R, you may also be interested checking out the first edition of Advanced R (http://adv-r.had.co.nz/). Some additional solutions related to that edition can be found at https://advanced-r-solutions-ed1.netlify.app/

There is one recommendation from Advanced R that we'd like to echo: reading source code can be tremendously helpful in developing your programming skill! For example, You can just head to GitHub and start looking into the source code of packages you love and developers you admire. While reading, it's not necessary to understand every line of code right away. Keeping this a regular practice (for a while) will expose you to many new ideas, patterns, design choices and also expand your R vocabulary.

We don't necessarily apply many of the concepts taught in Advanced R in daily programming and that's okay! But we hope that the code we write has become more robust, expressive and readable and it's actually quite easy to see the progress, when we take a look at the earlier drafts.

## Acknowledgements
Any open source project is actually the result of the work of a lot of people. We would like to explicitly mention and thank everybody who contributed solutions, raised questions or helped fix spelling and grammar.

```{r echo=FALSE, results='asis'}
contributors <- paste0(
  "`@", sort(unique(read.csv("contributors.csv")$username)), "`"
)

cat(paste0(contributors, collapse = ", "))
```

Thanks to CRC Press for the interest in the project and our editors Rob Calver and Vaishali Singh for their patience and support in making this book a reality.

Thanks to our managers and companies for granting us some flexibility with our work schedules and generally supporting the completion of this project.

## Conventions
A brief overview of conventions we followed and decisions we made.

- To spice things up a little the book we will sometimes reference Advanced R as a „textbook"
- Some chapters and sections in Advanced R do not contain exercises. In our book you will see that we skipped these chapters and sections. This decision introduces some gaps in the numbering, but we feel that keeping the numbers in sync with those of Advance R will provide the most practical value.
- We strived to follow the [Tidyverse Style Guide](https://style.tidyverse.org/) as much as possible (using `{styler}` made this a lot easier).
- `{bookdown}` will render each chapter in a separate R session. Initially each chapter will load the `{magrittr}` package to unlock the pipe operator, set a random seed (`1014`) to improve reproducibility and define a few `{ggplot2}` and `{knitr}` options. You can check out the (exact code)[https://GitHub.com/Tazinho/Advanced-R-Solutions/blob/main/common.R] on GitHub.
- We chose to to keep the code in this book as self-contained as possible. The packages used will be loaded in the beginning of each chapter. By default we will include all code necessary for the examples. When some longer code passages (from the textbook) were omitted this will be stated explicitly.

## Closing Remarks
We are so happy to finish this exciting project, that in fact neither of us really had the time for. We probably wouldn't have made it to the finish line if we hadn't worked on it together.

Collaboration is powerful and it's fun to build and share. The various backgrounds represented in the R community generally make this exchange much more interesting and meaningful. Much of this success is possible, because R is free software. At least in theory everyone can contribute and no one can take away your freedom to do so.

The automated systems we build using these tools are not neutral and the rapid adoption data-driven processes in business and technology does clearly affect our everyday lives and societies. It's important that  everyone  has a fair say in the discussions about these systems and participate in their design. Against this background we chose to donate half of our royalties from this book to https://rladies.org/, an organization empowering female R users.

Thank you for your interest in this project and we hope the solutions will be of value to you.

See you around!

Malte Grosser (`(@malte_grosser`)[https://twitter.com/malte_grosser])

Henning Bumann ((`@henningsway`)[https://twitter.com/henningsway])