# Environments

## Environment basics

1. List three ways in which an environment differs from a list.

2. If you don’t supply an explicit environment, where do ls() and rm() look? Where does <- make bindings?

3. Using parent.env() and a loop (or a recursive function), verify that the ancestors of globalenv() include baseenv() and emptyenv(). Use the same basic idea to implement your own version of search().

## Recursing over environments

1. Modify where() to find all environments that contain a binding for name.

2. Write your own version of get() using a function written in the style of where().

3. Write a function called fget() that finds only function objects. It should have two arguments, name and env, and should obey the regular scoping rules for functions: if there’s an object with a matching name that’s not a function, look in the parent. For an added challenge, also add an inherits argument which controls whether the function recurses up the parents or only looks in one environment.

4. Write your own version of exists(inherits = FALSE) (Hint: use ls().) Write a recursive version that behaves like exists(inherits = TRUE).

## Function environments

1. List the four environments associated with a function. What does each one do? Why is the distinction between enclosing and binding environments particularly important?

2. Draw a diagram that shows the enclosing environments of this function:

    f1 <- function(x1) {
      f2 <- function(x2) {
        f3 <- function(x3) {
          x1 + x2 + x3
        }
        f3(3)
      }
      f2(2)
    }
    f1(1)

3. Expand your previous diagram to show function bindings.

4. Expand it again to show the execution and calling environments.

5. Write an enhanced version of str() that provides more information about functions. Show where the function was found and what environment it was defined in.

## Binding names to values

1. What does this function do? How does it differ from <<- and why might you prefer it?

    rebind <- function(name, value, env = parent.frame()) {
      if (identical(env, emptyenv())) {
        stop("Can't find ", name, call. = FALSE)
      } else if (exists(name, envir = env, inherits = FALSE)) {
        assign(name, value, envir = env)
      } else {
        rebind(name, value, parent.env(env))
      }
    }
    rebind("a", 10)
    #> Error: Can't find a
    a <- 5
    rebind("a", 10)
    a
    #> [1] 10

2. Create a version of assign() that will only bind new names, never re-bind old names. Some programming languages only do this, and are known as single assignment languages.

3. Write an assignment function that can do active, delayed, and locked bindings. What might you call it? What arguments should it take? Can you guess which sort of assignment it should do based on the input?

