# Functionals

## For loops functionals: friends fo lapply():

1. Use vapply() to:

        Compute the standard deviation of every column in a numeric data frame.

        Compute the standard deviation of every numeric column in a mixed data frame. (Hint: you’ll need to use vapply() twice.)

2. Why is using sapply() to get the class() of each element in a data frame dangerous?

3.  The following code simulates the performance of a t-test for non-normal data. Use sapply() and an anonymous function to extract the p-value from every trial.

    trials <- replicate(
      100, 
      t.test(rpois(10, 10), rpois(7, 10)),
      simplify = FALSE
    )

    Extra challenge: get rid of the anonymous function by using [[ directly.

4. What does replicate() do? What sort of for loop does it eliminate? Why do its arguments differ from lapply() and friends?

5. Implement a version of lapply() that supplies FUN with both the name and the value of each component.

6. Implement a combination of Map() and vapply() to create an lapply() variant that iterates in parallel over all of its inputs and stores its outputs in a vector (or a matrix). What arguments should the function take?

7. Implement mcsapply(), a multicore version of sapply(). Can you implement mcvapply(), a parallel version of vapply()? Why or why not?


## Manipulating matrices and data frames

1. How does apply() arrange the output? Read the documentation and perform some experiments.

2. There’s no equivalent to split() + vapply(). Should there be? When would it be useful? Implement one yourself.

3. Implement a pure R version of split(). (Hint: use unique() and subsetting.) Can you do it without a for loop?

4. What other types of input and output are missing? Brainstorm before you look up some answers in the plyr paper.

## Manipulating lists

1. Why isn’t is.na() a predicate function? What base R function is closest to being a predicate version of is.na()?

2. Use Filter() and vapply() to create a function that applies a summary statistic to every numeric column in a data frame.

3. What’s the relationship between which() and Position()? What’s the relationship between where() and Filter()?

4. Implement Any(), a function that takes a list and a predicate function, and returns TRUE if the predicate function returns TRUE for any of the inputs. Implement All() similarly.

5. Implement the span() function from Haskell: given a list x and a predicate function f, span returns the location of the longest sequential run of elements where the predicate is true. (Hint: you might find rle() helpful.)

## Mathematical functionals

1. Implement arg_max(). It should take a function and a vector of inputs, and return the elements of the input where the function returns the highest value. For example, arg_max(-10:5, function(x) x ^ 2) should return -10. arg_max(-5:5, function(x) x ^ 2) should return c(-5, 5). Also implement the matching arg_min() function.

2. Challenge: read about the fixed point algorithm. Complete the exercises using R.

## A family of functions

1. Implement smaller and larger functions that, given two inputs, return either the smaller or the larger value. Implement na.rm = TRUE: what should the identity be? (Hint: smaller(x, smaller(NA, NA, na.rm = TRUE), na.rm = TRUE) must be x, so smaller(NA, NA, na.rm = TRUE) must be bigger than any other value of x.) Use smaller and larger to implement equivalents of min(), max(), pmin(), pmax(), and new functions row_min() and row_max().

2. Create a table that has and, or, add, multiply, smaller, and larger in the columns and binary operator, reducing variant, vectorised variant, and array variants in the rows.

        Fill in the cells with the names of base R functions that perform each of the roles.

        Compare the names and arguments of the existing R functions. How consistent are they? How could you improve them?

        Complete the matrix by implementing any missing functions.

3. How does paste() fit into this structure? What is the scalar binary function that underlies paste()? What are the sep and collapse arguments to paste() equivalent to? Are there any paste variants that don’t have existing R implementations?