# Expressions

## Structure of expressions

1. There’s no existing base function that checks if an element is a valid component of an expression (i.e., it’s a constant, name, call, or pairlist). Implement one by guessing the names of the “is” functions for calls, names, and pairlists.

    pryr::ast() uses non-standard evaluation. What’s its escape hatch to standard evaluation?

2. What does the call tree of an if statement with multiple else conditions look like?

3. Compare ast(x + y %+% z) to ast(x ^ y %+% z). What do they tell you about the precedence of custom infix functions?

4. Why can’t an expression contain an atomic vector of length greater than one? Which one of the six types of atomic vector can’t appear in an expression? Why?

## Names

1. You can use formals() to both get and set the arguments of a function. Use formals() to modify the following function so that the default value of x is missing and y is 10.

    g <- function(x = 20, y) {
      x + y
    }

2. Write an equivalent to get() using as.name() and eval(). Write an equivalent to assign() using as.name(), substitute(), and eval(). (Don’t worry about the multiple ways of choosing an environment; assume that the user supplies it explicitly.)

## Calls

1. The following two calls look the same, but are actually different:

    (a <- call("mean", 1:10))
    #> mean(1:10)
    (b <- call("mean", quote(1:10)))
    #> mean(1:10)
    identical(a, b)
    #> [1] FALSE

    What’s the difference? Which one should you prefer?

2. Implement a pure R version of do.call().

3.  Concatenating a call and an expression with c() creates a list. Implement concat() so that the following code works to combine a call and an additional argument.

    concat(quote(f), a = 1, b = quote(mean(a)))
    #> f(a = 1, b = mean(a))

4.  Since list()s don’t belong in expressions, we could create a more convenient call constructor that automatically combines lists into the arguments. Implement make_call() so that the following code works.

    make_call(quote(mean), list(quote(x), na.rm = TRUE))
    #> mean(x, na.rm = TRUE)
    make_call(quote(mean), quote(x), na.rm = TRUE)
    #> mean(x, na.rm = TRUE)

5. How does mode<- work? How does it use call()?

6. Read the source for pryr::standardise_call(). How does it work? Why is is.primitive() needed?

7.  standardise_call() doesn’t work so well for the following calls. Why?

    standardise_call(quote(mean(1:10, na.rm = TRUE)))
    #> mean(x = 1:10, na.rm = TRUE)
    standardise_call(quote(mean(n = T, 1:10)))
    #> mean(x = 1:10, n = T)
    standardise_call(quote(mean(x = 1:10, , TRUE)))
    #> mean(x = 1:10, , TRUE)

8. Read the documentation for pryr::modify_call(). How do you think it works? Read the source code.

9. Use ast() and experimentation to figure out the three arguments in an if() call. Which components are required? What are the arguments to the for() and while() calls?

## Capturing the current call

1. Compare and contrast update_model() with update.default().

2. Why doesn’t write.csv(mtcars, "mtcars.csv", row = FALSE) work? What property of argument matching has the original author forgotten?

3. Rewrite update.formula() to use R code instead of C code.

4. Sometimes it’s necessary to uncover the function that called the function that called the current function (i.e., the grandparent, not the parent). How can you use sys.call() or match.call() to find this function?

## Pairlists

1. How are alist(a) and alist(a = ) different? Think about both the input and the output.

2. Read the documentation and source code for pryr::partial(). What does it do? How does it work? Read the documentation and source code for pryr::unenclose(). What does it do and how does it work?

3. The actual implementation of curve() looks more like

    curve3 <- function(expr, xlim = c(0, 1), n = 100,
                       env = parent.frame()) {
      env2 <- new.env(parent = env)
      env2$x <- seq(xlim[1], xlim[2], length = n)

      y <- eval(substitute(expr), env2)
      plot(env2$x, y, type = "l", 
        ylab = deparse(substitute(expr)))
    }

 How does this approach differ from curve2() defined above?

## Parsing and deparsing

1. What are the differences between quote() and expression()?

2. Read the help for deparse() and construct a call that deparse() and parse() do not operate symmetrically on.

3. Compare and contrast source() and sys.source().

4. Modify simple_source() so it returns the result of every expression, not just the last one.

5. The code generated by simple_source() lacks source references. Read the source code for sys.source() and the help for srcfilecopy(), then modify simple_source() to preserve source references. You can test your code by sourcing a function that contains a comment. If successful, when you look at the function, you’ll see the comment and not just the source code.

## Walking the AST with recursive functions

1. Why does logical_abbr() use a for loop instead of a functional like lapply()?

2. logical_abbr() works when given quoted objects, but doesn’t work when given an existing function, as in the example below. Why not? How could you modify logical_abbr() to work with functions? Think about what components make up a function.

    f <- function(x = TRUE) {
      g(x + T)
    }
    logical_abbr(f)

3. Write a function called ast_type() that returns either “constant”, “name”, “call”, or “pairlist”. Rewrite logical_abbr(), find_assign(), and bquote2() to use this function with switch() instead of nested if statements.

4. Write a function that extracts all calls to a function. Compare your function to pryr::fun_calls().

5. Write a wrapper around bquote2() that does non-standard evaluation so that you don’t need to explicitly quote() the input.

6. Compare bquote2() to bquote(). There is a subtle bug in bquote(): it won’t replace calls to functions with no arguments. Why?

    bquote(.(x)(), list(x = quote(f)))
    #> .(x)()
    bquote(.(x)(1), list(x = quote(f)))
    #> f(1)

7. Improve the base recurse_call() template to also work with lists of functions and expressions (e.g., as from parse(path_to_file)).