```{r, include=FALSE}
source("common.R")
```

# Rewriting R code in C++

## Getting started with C++

1. __[Q]{.Q}__: With the basics of C++ in hand, it's now a great time to practice by reading and writing some simple C++ functions. For each of the following functions, read the code and figure out what the corresponding base R function is. You might not understand every part of the code yet, but you should be able to figure out the basics of what the function does.

    ```cpp
    double f1(NumericVector x) {
      int n = x.size();
      double y = 0;
    
      for(int i = 0; i < n; ++i) {
        y += x[i] / n;
      }
      return y;
    }
    
    NumericVector f2(NumericVector x) {
      int n = x.size();
      NumericVector out(n);
    
      out[0] = x[0];
      for(int i = 1; i < n; ++i) {
        out[i] = out[i - 1] + x[i];
      }
      return out;
    }
    
    bool f3(LogicalVector x) {
      int n = x.size();
    
      for(int i = 0; i < n; ++i) {
        if (x[i]) return true;
      }
      return false;
    }
    
    int f4(Function pred, List x) {
      int n = x.size();
    
      for(int i = 0; i < n; ++i) {
        LogicalVector res = pred(x[i]);
        if (res[0]) return i + 1;
      }
      return 0;
    }
    
    NumericVector f5(NumericVector x, NumericVector y) {
      int n = std::max(x.size(), y.size());
      NumericVector x1 = rep_len(x, n);
      NumericVector y1 = rep_len(y, n);
    
      NumericVector out(n);
    
      for (int i = 0; i < n; ++i) {
        out[i] = std::min(x1[i], y1[i]);
      }
    
      return out;
    }
    ```

   __[A]{.solved}__:  The R equivalents are:

   *   f1: `mean()`  
   *   f2: `cumsum()`  
   *   f3: `any()`
   *   f4: `Position()`
   *   f5: `pmin()`

1. __[Q]{.Q}__:  To practice your function writing skills, convert the following functions into C++. For now, assume the inputs have no missing values.
  
    1. `all()`.
    
    2. `cumprod()`, `cummin()`, `cummax()`.
    
    3. `diff()`. Start by assuming lag 1, and then generalise for lag `n`.
    
    4. `range()`.
    
    5. `var()`. Read about the approaches you can take on 
       [Wikipedia](http://en.wikipedia.org/wiki/Algorithms_for_calculating_variance).
       Whenever implementing a numerical algorithm, it's always good to check 
       what is already known about the problem.

   __[A]{.solved}__:
   
   1. `all()`
  
    ```cpp
    bool allC(LogicalVector x) {
      int n = x.size();
      
      for(int i = 0; i < n; ++i) {
        if (!x[i]) return false;
      }
      return true;
    }
    ```
  
   2. `cumprod()`, `cummin()`, `cummax()`.
  
    ```cpp
    NumericVector cumprodC(NumericVector x) {
      
      int n = x.size();
      NumericVector out(n);
      
      out[0] = x[0];
      for(int i = 1; i < n; ++i) {
        out[i]  = out[i - 1] * x[i];
      }
      return out;
    }

    NumericVector cumminC(NumericVector x) {
      int n = x.size();
      NumericVector out(n);
    
      out[0] = x[0];
      for(int i = 1; i < n; ++i) {
        out[i]  = std::min(out[i - 1], x[i]);
      }
      return out;
    }
    
    NumericVector cummaxC(NumericVector x) {
      int n = x.size();
      NumericVector out(n);
    
      out[0] = x[0];
      for(int i = 1; i < n; ++i) {
        out[i]  = std::max(out[i - 1], x[i]);
      }
    return out;
    }
    ```

   3. `diff()`. Start by assuming lag 1, and then generalise for lag `n`.
    
    ```cpp
    NumericVector diffC(NumericVector x){
      int n = x.size();
      NumericVector out(n - 1);
      
      for(int i = 1; i < n; i++){
          out[i - 1] = x[i] - x[i - 1];
      }
      return out ;
    }

    NumericVector difflagC(NumericVector x, int lag){
      int n = x.size();
      NumericVector out(n - lag);
              
      for(int i = lag; i < n; i++){
          out[i - lag] = x[i] - x[i - lag];
      }
      return out;
    }'
    ```
  
   4. `range`.  
    
    ```cpp
    NumericVector rangeC(NumericVector x){
      double omin, omax;  
      int n = x.size();
      NumericVector out(2);
  
      omin = x[0];
      omax = x[0];

      for(int i = 1; i < n; i++){
          omin = std::min(x[i], omin);
          omax = std::max(x[i], omax);
      }

      out[0] = omin;
      out[1] = omax;
      return out;
    ```
  
   5. `var`. Read about the approaches you can take on [wikipedia](http://en.wikipedia.org/wiki/Algorithms_for_calculating_variance). Whenever implementing a numerical algorithm, it's always good to check what is already known about the problem.
   
    ```cpp
    double varC(NumericVector x) {
      int n = x.size();
      double mx = 0;
      double out = 0;
      
      if(n < 2) {
        return NA_REAL;
      }
      
      for(int i = 0; i < n; ++i) {
        mx += x[i] / n;
      }
      
      for(int i = 0; i < n; ++i) {
        out += pow(x[i] - mx, 2);
      }
      
      out = out / (n-1);
      return out;
    }
    ```

## Missing values

1. __[Q]{.Q}__:  Rewrite any of the functions from the first exercise to deal with missing values. If `na.rm` is true, ignore the missing values. If `na.rm` is false, return a missing value if the input contains any missing values. Some good functions to practice with are `min()`, `max()`, `range()`, `mean()`, and `var()`.

   __[A]{.started}__: (TODO: `var`'s implementation is still missing. The functions from the 1st (NOT THE SECOND EXERCISE) need to be (also/especially) solved)
   
   Let's follow the advice and rewrite `min()`, `max()`, `range()`, `mean()` and `var()` first. After this, we look at `cumsum()`, `any()`, `Position()` and `pmin()` from the first exercise.
   
   To make `minC()` aware of `NA`s, we introduce an `na_rm` argument and need to differ between the following cases:
    * `x` doesn't contain any NAs
    * `x` contains NAs and `na_rm = false`: return `NA_REAL`
    * `x` comtains only NAs and `na_rm = true`: return `R_PosInf`
    * `x` contains some NAs and `na_rm = true`

    ```cpp
    double minC(NumericVector x, bool na_rm = false){
      int n = x.size();
      LogicalVector i_na = is_na(x);
      double out = NA_REAL;
      bool any_na = false;
      bool all_na = true;
      
      // Calculate any_na
      for(int i = 0; i<n; i++){
        if (i_na[i]) {
          any_na = true;
          break;
        }
      }
      
      if (!any_na) {
        out = x[0];
        for(int i = 0; i < n; i++) {
          out = std::min(x[i], out);
        }
        return out;
      }
      
      if (!na_rm & any_na) {
        return out;
      }
      
      // Calculate all_na
      for(int i = 0; i < n; i++){
        if (!i_na[i]) {
          all_na = false;
          break;
        }
      }
      
      // Case any_na & na_rm
      if (na_rm & all_na) return R_PosInf;
      
      if (na_rm & any_na) {
        // Find start value
        for(int i = 0; i < n; i++){
          if (!i_na[i]) {
            out = x[i];
            break;
          }
        }
        // Calculate minimum
        for(int i = 0; i < n; i++) {
          if (!i_na[i]) {
            out = std::min(x[i], out);
          }
        }
      }
      
      return out;
    }
    ```
    
   To make `maxC()` aware of NAs, we follow our implementation of `minC()` and only change `std::min` to `std::max` and `R_PosInf` to `R_NegInf`.

    ```cpp
    double maxC(NumericVector x, bool na_rm = false){
      int n = x.size();
      LogicalVector i_na = is_na(x);
      double out = NA_REAL;
      bool any_na = false;
      bool all_na = true;
      
      // Calculate any_na
      for(int i = 0; i<n; i++){
        if (i_na[i]) {
          any_na = true;
          break;
        }
      }
  
      if (!any_na) {
        out = x[0];
        for(int i = 0; i < n; i++) {
          out = std::max(x[i], out);
        }
        return out;
      }
      
      if (!na_rm & any_na) {
        return out;
      }
      
      // Calculate all_na
      for(int i = 0; i < n; i++){
        if (!i_na[i]) {
          all_na = false;
          break;
        }
      }
      
      // Case any_na & na_rm
      if (na_rm & all_na) return R_NegInf;
      
      if (na_rm & any_na) {
        // Find start value
        for(int i = 0; i < n; i++){
          if (!i_na[i]) {
            out = x[i];
            break;
          }
        }
        // Calculate maximum
        for(int i = 0; i < n; i++) {
          if (!i_na[i]) {
            out = std::max(x[i], out);
          }
        }
      }
      
      return out;
    }
    ```
   
   `minC()` and `maxC()` enable us to write a compact and NA-aware `rangeC()` function.
   
    ```cpp    
    NumericVector rangeC(NumericVector x, bool na_rm = false){
      NumericVector out(2);
      
      out[0] = minC(x, na_rm);
      out[1] = maxC(x, na_rm);
      
      return out;
    }
    ```
    
   To make `meanC()` aware of `NAs`, we consider the same cases as in previous functions.
    
    ```cpp
    double meanC(NumericVector x, bool na_rm = false){
      int n = x.size();
      LogicalVector i_na = is_na(x);
      bool any_na = false;
      bool all_na = true;
      int n_non_na = 0;
      double out = 0;
  
      // Calculate any_na
      for(int i = 0; i<n; i++){
        if (i_na[i]) {
          any_na = true;
          break;
        }
      }
  
      if (!any_na) {
        for (int i = 0; i < n; i++) {
          out += x[i] / n;
        }
        return out;
      }
  
      // Calculate all_na and count of non-NAs
      for(int i = 0; i<n; i++){
          if (!i_na[i]) {
            all_na = false;
            n_non_na++;
          }
      }
    
      if (!na_rm & any_na) {
        return NA_REAL;
      }
    
      // Case na_rm and any_na
      if (na_rm & all_na) {
        return NAN;
      }
      
      if (na_rm) {
        for(int i = 0; i < n; i++) {
          if (!i_na[i]) out += x[i] / n_non_na;
        }
      }
  
      return out;
    }
    ```
    
   To make `varC()` aware of NAs, we need to cover the following cases:

    * `sum(!is.na(x)) <= 2`: return NA.
    * `x` contains `NA`s and `na_rm = false`: return `NA`
    * `x` doesn’t contain `NA`s and (`length(x) > 1`)
    * `x` contains `NA`s (but `sum(!is.na(x)) > 1`) and narm = true
    
    ```cpp
    double varC(NumericVector x, bool na_rm = false) {
      int n = x.size();
      LogicalVector i_na = is_na(x);
      int n_na = 0;
      double mx = 0;
      double out = 0;
      
      // Calculate n_na
      for(int i = 0; i<n; i++){
          if (i_na[i]) {
            n_na++;
          }
      }
      
      // sum(!is.na(x)) < 2: return NA
      if (n - n_na < 2) {return NA_REAL;}
      
      // x contains NAs an na_rm = false: return NA
      if (n_na > 0 & !na_rm) {return NA_REAL;}
      
      // x doesn’t contain NAs (and length(x) > 1):
      // n_na = 0 (and n > 1)
      if (n_na == 0) {
        for(int i = 0; i < n; ++i) {
          mx += x[i] / n;
        }
          
        for(int i = 0; i < n; ++i) {
          out += pow(x[i] - mx, 2);
        }
      
        out = out / (n-1);
      }
  
      // x contains NAs (but sum(!is.na(x)) > 1) and narm = true
      // n_na > 0 and narm = true
      if (n_na > 0 & na_rm) {
        for(int i = 0; i < n; ++i) {
          if (!i_na[i]) {
            mx += x[i] / (n - n_na);
          }
        }
      
        for(int i = 0; i < n; ++i) {
          if (!i_na[i]) {
            out += pow(x[i] - mx, 2);
          }
        }
      
        out = out / (n - n_na - 1);
      }
  
      return out;
    }
    ```

2. __[Q]{.Q}__: Rewrite `cumsum()` and `diff()` so they can handle missing values. Note that these functions have slightly more complicated behaviour.
    
   __[A]{.solved}__:
   
    ```cpp
    NumericVector cumsumC(NumericVector x) {
      int n = x.size();
      NumericVector out(n);
      LogicalVector index = is_na(x);
  
      out[0] = x[0];
      for(int i = 1; i < n; ++i) {
        if (index[i - 1]) {
          out[i] = NA_REAL;
      } else{
          out[i] = out[i - 1] + x[i];
        }
      }
    
      return out;
    }
    
    NumericVector difflagC(NumericVector x, int lag){
      int n = x.size();
      NumericVector out(n - lag);
      LogicalVector index = is_na(x);
              
      for(int i = lag; i < n; i++){
          if ((index[i]) || (index[i - lag])) {
              out[i - lag] = NA_REAL;
          } else {
              out[i - lag] = x[i] - x[i - lag];
          }
      }
      return out;
    }
    ```

## Standard Template Library

To practice using the STL algorithms and data structures, implement the following using R functions in C++, using the hints provided:

1. __[Q]{.Q}__: `median.default()` using `partial_sort`.

   __[A]{.solved}__:
   
    ```cpp
    #include <algorithm>
    #include <Rcpp.h>
    using namespace Rcpp;
    
    // [[Rcpp::export]]
    double medianC(NumericVector x) {
      int n = x.size();
      double out;
      if (n % 2 == 0){
        std::partial_sort (x.begin(), x.begin() + n / 2 + 1, x.end());
        out = (x[n / 2 - 1] + x[n / 2]) / 2;
      } else {
        std::partial_sort (x.begin(), x.begin() + (n + 1) / 2, x.end());
        out = x[(n + 1) / 2 - 1];
      }
      
      return out;
    }
    ```

2. __[Q]{.Q}__: `%in%` using `unordered_set` and the `find()` or `count()` methods.

   __[A]{.solved}__:

3. __[Q]{.Q}__: `unique()` using an `unordered_set` (challenge: do it in one line!).

   __[A]{.started}__: (TODO: address the challenge.)

    ```cpp
    // [[Rcpp::plugins(cpp11)]]
    #include <Rcpp.h>
    #include <unordered_set>
    using namespace Rcpp;
    
    // [[Rcpp::export]]
    NumericVector uniqueC(NumericVector x) {
      std::unordered_set<int> seen;
      int n = x.size();
      std::vector<double> out;
      
      for (int i = 0; i < n; ++i) {
        if (seen.insert(x[i]).second) out.push_back(x[i]);
        }
      
      return wrap(out);
    }
    ```

4. __[Q]{.Q}__: `min()` using `std::min()`, or `max()` using `std::max()`.

   __[A]{.solved}__:

    ```cpp
    #include <Rcpp.h>
    using namespace Rcpp;
    
    // [[Rcpp::export]]
    double minC(NumericVector x){
      int n = x.size();
      double out = x[0];
      
      for (int i = 0; i < n; i++){
        out = std::min(out, x[i]);
      }
      
      return out;
    }
    ```

5. __[Q]{.Q}__: `which.min()` using `min_element`, or `which.max()` using `max_element`.

   __[A]{.solved}__:

    ```cpp
    #include <Rcpp.h>
    #include <algorithm>
    #include <iterator>
    
    using namespace Rcpp;

    // [[Rcpp::export]]
    double which_minC(NumericVector x){
      int out;
      out = std::distance(x.begin(),std::min_element(x.begin(),x.end()));
      out++;
  
      return out;
    }
    ```

6. __[Q]{.Q}__: `setdiff()`, `union()`, and `intersect()` for integers using sorted ranges and `set_union`, `set_intersection` and `set_difference`.

   __[A]{.solved}__:
   
