project:
  type: book
  output-dir: docs
  
book:
  title: "Advanced R Solutions"
  author: "Malte Grosser, Henning Bumann, Hadley Wickham & Mauricio Vargas Sepulveda"
  description: "Solutions to the Exercises in Hadley Wickham's book 'Advanced R'."
  date: "2024-01-22"
  chapters:
    - index.qmd
    - 00_02_Preface.qmd
    - 00_03_Abstracts.qmd
    - part: "Foundations"
      chapters:
      - 02_Names_and_values.qmd
      - 03_Vectors.qmd
      - 04_Subsetting.qmd
      - 05_Control_flow.qmd
      - 06_Functions.qmd
      - 07_Environments.qmd
      - 08_Conditions.qmd
    - part: "Functional programming"
      chapters:
      - 09_Functionals.qmd
      - 10_Function_factories.qmd
      - 11_Function_operators.qmd
    - part: "Object-oriented programming"
      chapters: 
      - 13_S3.qmd
      - 14_R6.qmd
      - 15_S4.qmd
    - part: "Metaprogramming"
      chapters:
      - 18_Expressions.qmd
      - 19_Quasiquotation.qmd
      - 20_Evaluation.qmd
      - 21_Translating_R_code.qmd
    - part: Techniques
      chapters:
      - 23_Measuring_performance.qmd
      - 24_Improving_performance.qmd
      - 25_Rewriting_R_code_in_Cpp.qmd

format:
  html:
    theme: cosmo
