project:
  type: book
  output-dir: docs
  
book:
  title: "Advanced R Solutions"
  author: "Malte Grosser, Henning Bumann, Hadley Wickham & Mauricio Vargas Sepulveda"
  description: "Solutions to the Exercises in Hadley Wickham's book 'Advanced R'."
  date: "2024-01-22"
  chapters:
    - index.qmd
    - 01_Preface.qmd
    - part: "Foundations"
      chapters:
      - 02_Names_and_values.qmd
      - 03_Vectors.qmd
      - 04_Subsetting.qmd
      - 05_Control_flow.qmd
      - 06_Functions.qmd
      - 07_Environments.qmd
      - 08_Conditions.qmd
    - part: "Functional programming"
      chapters:
      - 09_Functionals.qmd
      - 10_Function_factories.qmd
      - 11_Function_operators.qmd
    - part: "Object-oriented programming"
      chapters: 
      - 12_S3.qmd
      - 13_R6.qmd
      - 14_S4.qmd

format:
  html:
    theme: cosmo
