--- 
title: "Advanced R Solutions"
author: "Malte Grosser & Henning Bumann"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: Tazinho/Advanced-R-Solutions
before_chapter_script: ["before_chapter_script_1.R"]
edit: 
  link: https://github.com/Tazinho/Advanced-R-Solutions/blob/master/%s
  text: "Edit"
description: "Solutions to the exercises in Hadley Wickhams book Advanced R."
---

# Prerequisites {-}

This book aims to contribute the solutions to Hadley Wickhams book [Advanced R](http://adv-r.had.co.nz/).
It is planed to finish until end of 2016. The code is [online](https://github.com/Tazinho/Advanced-R-Solutions.git).

The date of the exercise versions is September 9th 2016.

```{r eval=FALSE, echo = FALSE}
devtools::install_github("rstudio/bookdown")
date()
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
