---
format:
  pdf:
    pdf-engine: xelatex
    dev: cairo_pdf
    highlight: tango
    keep-tex: true
    citation_package: natbib
    documentclass: krantz
    bibliography: references.bib
    csl: chicago-fullnote-bibliography.csl
    includes:
      in_header: latex/preamble.tex
      before_body: latex/before_body.tex
      after_body: latex/after_body.tex
---

\frontmatter

```{r fm}
#| child: 00_02_Preface.qmd
```

\mainmatter

\part{Foundations}

```{r ch2}
#| context: ch02
#| child: "02_Names_and_values.qmd"
```

```{r ch3}
#| context: ch03
#| child: "03_Vectors.qmd"
```

```{r ch4}
#| context: ch04
#| child: "04_Subsetting.qmd"
```

```{r ch5}
#| context: ch05
#| child: "05_Control_flow.qmd"
```

```{r ch6}
#| context: ch06
#| child: "06_Functions.qmd"
```

```{r ch7}
#| context: ch07
#| child: "07_Environments.qmd"
```

```{r ch8}
#| context: ch08
#| child: "08_Conditions.qmd"
```

\part{Functional programming}

```{r ch9}
#| context: ch09
#| child: "09_Functionals.qmd"
```

```{r ch10}
#| context: ch10
#| child: "10_Function_factories.qmd"
```

```{r ch11}
#| context: ch11
#| child: "11_Function_operators.qmd"
```

\part{Object-oriented programming}

```{r ch13}
#| context: ch13
#| child: "13_S3.qmd"
```

```{r ch14}
#| context: ch14
#| child: "14_R6.qmd"
```

```{r ch15}
#| context: ch15
#| child: "15_S4.qmd"
```

\part{Metaprogramming}

```{r ch18}
#| context: ch18
#| child: "18_Expressions.qmd"
```

```{r ch19}
#| context: ch19
#| child: "19_Quasiquotation.qmd"
```

```{r ch20}
#| context: ch20
#| child: "20_Evaluation.qmd"
```

```{r ch21}
#| context: ch21
#| child: "21_Translating_R_code.qmd"
```

\part{Techniques}

```{r ch23}
#| context: ch23
#| child: "23_Measuring_performance.qmd"
```

```{r ch24}
#| context: ch24
#| child: "24_Improving_performance.qmd"
```

```{r ch25}
#| context: ch25
#| child: "25_Rewriting_R_code_in_Cpp.qmd"
```
